### PR TITLE
Update and rename 2020-09-25-nishma-laitonjam20a.md to 2020-09-25-lai…

### PR DESCRIPTION
**Pull request by weipeng**
…tonjam20a.md

Hi Neil,

Following what you suggested, I changed the author list as well as the corresponding folder name and file names.

Please do let me know if I have done this correctly.

### CODE REVIEW

**Review by lawrennd — CHANGES_REQUESTED** [review]
Hi Weipeng,

Nearly there, I think you need to also change the name of the underlying directories in github too and the actual pdf file names ... not just the ones in this markdown file.

Thanks!

Neil

**Comment by weipeng** [comment]
Hi Neil,

Just tried a few ways of changing the folder name and the file names but failed. Appreciate that if you can give me some quick guidance.

**Comment by lawrennd** [comment]
Let me merge this and see if I can manage directly.

**Comment by lawrennd** [comment]
Hi Weipeng. I think doing it online is hard, you basically have to clone the repo on your local computer and do it there. Since I already have that repo cloned, I've just made those filename changes and pushed them. Can you double check it's all working OK? It may take a while for the changes to propagate to the website.

In particular, links to pdf and supplementary material should still be working. And also check the bib file entry is correct.

**Comment by weipeng** [comment]
Hi Neil. 

I have checked the bib file and the links to both the main paper and the supplemental file, and cannot find any problem so far. 

Thank you so much for your time!

**Comment by lawrennd** [comment]
Thank you for contributing the fix Weipeng!

**Pull request merged**
